image: registry.gitlab.heu.group/docker-tools/pipelines:v8.13

variables:
  IMAGE_REPOSITORY: "$CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG"
  IMAGE_TAG: "$CI_COMMIT_SHA"
  KUBE_NAMESPACE: product-price

stages:
  - build
  - test
  - lint
  - deploy

include:
  - local: .gitlab/ci/build.yaml
  - local: .gitlab/ci/test.yaml
  - local: .gitlab/ci/lint.yaml
  - local: .gitlab/ci/deploy.yaml
