app:
  env: prod

ingress:
  host: api.product-price.prod.heu.group

postgres:
  masterHost: ""  # The database instance will be created later

redis:
  host: 10.116.1.3

rabbitmq:
  host: 10.112.1.32 # prod-rmq-cl-2.rabbitmq.prod.heu.group

autoscaling:
  api:
    enabled: true
    minReplicas: 3
    maxReplicas: 6
