app:
  env: prod

ingress:
  host: api.product-price.prod.heu.group

postgres:
  masterHost: 10.116.0.140  # The database instance will be created later

redis:
  host: 10.116.1.4

rabbitmq:
  host: 10.112.1.32 # prod-rmq-cl-2.rabbitmq.prod.heu.group
  entities:
    availability:
      rmqHost: 10.112.1.33 # prod-rmq-cl-5.rabbitmq.prod.heu.group

autoscaling:
  api:
    enabled: true
    minReplicas: 3
    maxReplicas: 6
  consumer:
    pollingInterval: 10
    minReplicaCount: 1
    maxReplicaCount: 12
  workers:
    pollingInterval: 10
    minReplicaCount: 1
    maxReplicaCount: 12
