"""drop offer table

Revision ID: ea0707fff91f
Revises: 77c3f095f32f
Create Date: 2024-04-29 08:52:46.212801

"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "ea0707fff91f"
down_revision = "77c3f095f32f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("offers")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "offers",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("product_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("shop_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "country_code",
            postgresql.ENUM(
                "BA", "BG", "HR", "CZ", "HU", "RO", "RS", "SI", "SK", name="countrycode"
            ),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "currency_code",
            postgresql.ENUM(
                "BAM",
                "EUR",
                "BGN",
                "HRK",
                "CZK",
                "HUF",
                "RON",
                "RSD",
                name="currencycode",
            ),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("price", sa.NUMERIC(), autoincrement=False, nullable=False),
        sa.Column("version", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("in_stock", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column(
            "availability_version", sa.BIGINT(), autoincrement=False, nullable=False
        ),
        sa.Column("buyable", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("buyable_version", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="offers_pkey"),
    )
    op.create_index("ix_offers_id", "offers", ["id"], unique=False)
    # ### end Alembic commands ###
