"""indexing offers.shop_id

Revision ID: 3347f9987704
Revises: 8a48744218a7
Create Date: 2024-05-06 13:46:25.856962

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "3347f9987704"
down_revision = "8a48744218a7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_offers_shop_id"), "offers", ["shop_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_offers_shop_id"), table_name="offers")
    # ### end Alembic commands ###
