"""init-database

Revision ID: 0f829de42ead
Revises:
Create Date: 2024-04-12 13:51:16.489968

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "0f829de42ead"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "availabilities",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "country_code",
            sa.Enum(
                "BA", "BG", "HR", "CZ", "HU", "RO", "RS", "SI", "SK", name="countrycode"
            ),
            nullable=False,
        ),
        sa.Column("in_stock", sa.Boolean(), server_default="False", nullable=False),
        sa.Column("version", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_availabilities")),
    )
    op.create_table(
        "buyables",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "country_code",
            sa.Enum(
                "BA", "BG", "HR", "CZ", "HU", "RO", "RS", "SI", "SK", name="countrycode"
            ),
            nullable=False,
        ),
        sa.Column("buyable", sa.Boolean(), server_default="False", nullable=False),
        sa.Column("version", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_buyables")),
    )
    op.create_table(
        "offers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("shop_id", sa.UUID(), nullable=False),
        sa.Column(
            "country_code",
            sa.Enum(
                "BA", "BG", "HR", "CZ", "HU", "RO", "RS", "SI", "SK", name="countrycode"
            ),
            nullable=False,
        ),
        sa.Column(
            "currency_code",
            sa.Enum(
                "BAM",
                "EUR",
                "BGN",
                "HRK",
                "CZK",
                "HUF",
                "RON",
                "RSD",
                name="currencycode",
            ),
            nullable=False,
        ),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("version", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_offers")),
    )
    op.create_index(op.f("ix_offers_product_id"), "offers", ["product_id"], unique=False)
    op.create_table(
        "shops",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "country_code",
            sa.Enum(
                "BA", "BG", "HR", "CZ", "HU", "RO", "RS", "SI", "SK", name="countrycode"
            ),
            nullable=False,
        ),
        sa.Column("certified", sa.Boolean(), server_default="False", nullable=False),
        sa.Column("verified", sa.Boolean(), server_default="False", nullable=False),
        sa.Column("paying", sa.Boolean(), server_default="False", nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default="False", nullable=False),
        sa.Column("version", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_shops")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("shops")
    op.drop_index(op.f("ix_offers_product_id"), table_name="offers")
    op.drop_table("offers")
    op.drop_table("buyables")
    op.drop_table("availabilities")
    # ### end Alembic commands ###
