"""add base_price table

Revision ID: 5d0213c2e410
Revises: 8a48744218a7
Create Date: 2024-05-13 13:32:22.531389

"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "5d0213c2e410"
down_revision = "3347f9987704"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "base_prices",
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column(
            "price_type",
            postgresql.ENUM(
                name="product_price_type",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("product_id", "price_type", name=op.f("pk_base_prices")),
        postgresql_partition_by="HASH (product_id)",
    )
    # ### end Alembic commands ###

    for i in range(10):
        op.execute(
            f"""
                CREATE TABLE base_prices_{i:02d} PARTITION OF base_prices
                FOR VALUES WITH (MODULUS 10, REMAINDER {i})
            """
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("base_prices")
    # ### end Alembic commands ###
