"""change offer price column name

Revision ID: f3ee8d983179
Revises: 0f829de42ead
Create Date: 2024-04-14 08:54:22.645762

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "f3ee8d983179"
down_revision = "0f829de42ead"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "offers", sa.Column("price", sa.Numeric(precision=12, scale=2), nullable=False)
    )
    op.drop_column("offers", "amount")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "offers",
        sa.Column(
            "amount",
            sa.NUMERIC(precision=12, scale=2),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("offers", "price")
    # ### end Alembic commands ###
