"""Add product table

Revision ID: 425d1fc27306
Revises:
Create Date: 2023-09-05 13:35:34.030759

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "425d1fc27306"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "products",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("local_product_id", sa.String(length=32), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("country", sa.String(length=2), nullable=False),
        sa.Column("version", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_products")),
    )
    op.create_index(op.f("ix_products_country"), "products", ["country"], unique=False)
    op.create_index(
        "ix_products_local_key",
        "products",
        ["local_product_id", "country"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_products_local_key", table_name="products")
    op.drop_index(op.f("ix_products_country"), table_name="products")
    op.drop_table("products")
    # ### end Alembic commands ###
