"""create partion tables

Revision ID: 735f11dd2cd8
Revises: 7a9f97dc1b9b
Create Date: 2023-10-29 13:52:29.333379

"""
from alembic import op
from app.db.pg import (
    generate_create_partition_table_sql,
    generate_drop_partition_table_sql,
)

# revision identifiers, used by Alembic.
revision = "735f11dd2cd8"
down_revision = "7a9f97dc1b9b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    for i in range(10, 13):
        op.execute(generate_create_partition_table_sql(2023, i))
    for i in range(1, 13):
        op.execute(generate_create_partition_table_sql(2024, i))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    for i in range(10, 13):
        op.execute(generate_drop_partition_table_sql(2023, i))
    for i in range(1, 13):
        op.execute(generate_drop_partition_table_sql(2024, i))
    # ### end Alembic commands ###
