"""fix column name

Revision ID: 7a9f97dc1b9b
Revises: 4f28ebf04082
Create Date: 2023-10-26 12:48:19.112193

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "7a9f97dc1b9b"
down_revision = "4f28ebf04082"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("shops", "certified", new_column_name="certificated")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("shops", "certificated", new_column_name="certified")
    # ### end Alembic commands ###
