apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "product-price.fullname" . }}-api
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "product-price.labels" . | nindent 4 }} api
data:
  PPS_APP_ENV: {{ .Values.app.env | quote }}
  PPS_LOG_LEVEL: {{ .Values.app.logLevel | quote }}
  PPS_LOG_FORMAT: {{ .Values.app.logFormat | quote }}
  PPS_POSTGRES_DB_HOST: {{ .Values.postgres.masterHost | quote }}
  PPS_POSTGRES_DB_NAME: {{ .Values.postgres.dbName | quote }}
  PPS_POSTGRES_DB_USER: {{ .Values.postgres.user | quote }}
