apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "product-price.fullname" . }}-api
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "product-price.labels" . | nindent 4 }} api
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: {{ .Release.Namespace }}
    kind: SecretStore
  target:
    name: {{ include "product-price.fullname" . }}-api
  data:
    - secretKey: PPS_POSTGRES_DB_PASSWORD
      remoteRef:
        key: kv-product-price/postgresql
        property: DATABASE_PASSWORD
    - secretKey: PPS_APP_SECRET
      remoteRef:
        key: kv-product-price/app
        property: APP_SECRET
