apiVersion: v1
kind: Service
metadata:
  name: {{ include "product-price.fullname" . }}-api
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "product-price.labels" . | nindent 4 }} api
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "product-price.selectorLabels" . | nindent 4 }} api
