apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "product-price.fullname" . }}-api
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "product-price.labels" . | nindent 4 }} api
spec:
  {{- if not .Values.autoscaling.api.enabled }}
  replicas: {{ .Values.autoscaling.api.minReplicas }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "product-price.selectorLabels" . | nindent 6 }} api
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "product-price.labels" . | nindent 8 }} api
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-api
          command: ["/usr/src/app/scripts/run-api.sh"]
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          envFrom:
            - secretRef:
                name: {{ include "product-price.fullname" . }}-api
            - configMapRef:
                name: {{ include "product-price.fullname" . }}-api
          livenessProbe:
            {{- toYaml .Values.livenessProbe.api | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe.api | nindent 12 }}
          resources:
            {{- toYaml .Values.resources.api | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
