apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "product-price.fullname" . }}-consumer
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "product-price.labels" . | nindent 4 }} consumer
data:
  PPS_APP_ENV: {{ .Values.app.env | quote }}
  PPS_LOG_LEVEL: {{ .Values.app.logLevel | quote }}
  PPS_LOG_FORMAT: {{ .Values.app.logFormat | quote }}
  PPS_REDIS_HOST: {{ .Values.redis.host | quote }}
  PPS_RABBITMQ_HOST: {{ .Values.rabbitmq.host | quote }}
  PPS_RABBITMQ_PORT: {{ .Values.rabbitmq.port | quote }}
  PPS_RABBITMQ_USER: {{ .Values.rabbitmq.user | quote }}
  PPS_POSTGRES_DB_HOST: {{ .Values.postgres.masterHost | quote }}
  PPS_POSTGRES_DB_NAME: {{ .Values.postgres.dbName | quote }}
  PPS_POSTGRES_DB_USER: {{ .Values.postgres.user | quote }}
  PPS_RABBITMQ_VIRTUAL_HOST: {{ .Values.rabbitmq.virtualhost | quote }}
  PPS_RABBITMQ_EXCHANGE_NAME: {{ .Values.rabbitmq.exchange | quote }}
  PPS_RABBITMQ_PREFETCH_COUNT: {{ .Values.rabbitmq.prefetchCount | quote }}
  PPS_RABBITMQ_ENTITY_SERVER_MAP: {{ .Values.rabbitmq.entities | toJson | squote }}
  PPS_CONSUMER_RABBITMQ_CREATE_QUEUES: {{ .Values.consumers.createQueues | quote }}
  PPS_CONSUMER_RABBITMQ_QUEUE_MAPPING: {{ .Values.consumers.queues | toJson | squote }}
  PPS_CONSUMER_RABBITMQ_ENTITIES: {{ .Values.consumers.entities | toJson | squote }}
  PPS_CONSUMER_RABBITMQ_QUEUE_POSTFIX: {{ .Values.rabbitmq.queuePostfix | quote }}
  PPS_CONSUMER_MAX_DELAY: {{ .Values.consumers.redisPushInterval | quote }}
  PPS_CONSUMER_REDIS_CAPACITY_THRESHOLD_IN_PERCENT: {{ .Values.consumers.redisCapacityThreshold | quote }}
  PPS_SENTRY_DSN: {{ .Values.sentry.dsn | quote }}
