{{- range $name, $configValues := .Values.jobs -}}
{{- with $ }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.deployment.name }}-job-{{ $name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "product-price.labels" . | nindent 4 }} job-{{ $name }}
data:
  PPS_APP_ENV: {{ .Values.app.env | quote }}
  PPS_LOG_LEVEL: {{ .Values.app.logLevel | quote }}
  PPS_LOG_FORMAT: {{ .Values.app.logFormat | quote }}
  PPS_POSTGRES_DB_HOST: {{ .Values.postgres.masterHost | quote }}
  PPS_POSTGRES_DB_NAME: {{ .Values.postgres.dbName | quote }}
  PPS_POSTGRES_DB_USER: {{ .Values.postgres.user | quote }}
  PPS_REDIS_HOST: {{ .Values.redis.host | quote }}
  PPS_JOB_BATCH_SIZE: {{ $configValues.batchSize | quote }}
  PPS_JOB_QUEUE_POP_TIMEOUT: {{ $configValues.queuePopTimeout | quote }}
  PPS_SENTRY_DSN: {{ .Values.sentry.dsn | quote }}
{{- end -}}
{{- end -}}
