{{- if .Values.autoscaling.job.enabled }}
{{- range $name, $configValues := .Values.jobs -}}
{{- with $ }}
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ .Values.deployment.name }}-job-{{ $name }}-keda
  labels:
    {{- include "product-price.labels" . | nindent 4 }} job-{{ $name }}
  namespace: {{ .Release.Namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.deployment.name }}-job-{{ $name }}
  pollingInterval: {{ $configValues.autoscalingPollingInterval | default .Values.autoscaling.job.pollingInterval }}
  minReplicaCount: {{ $configValues.autoscalingMinReplicaCount | default .Values.autoscaling.job.minReplicaCount }}
  maxReplicaCount: {{ $configValues.autoscalingMaxReplicaCount | default .Values.autoscaling.job.maxReplicaCount }}
  advanced:
    {{- toYaml ($configValues.autoscalingAdvanced | default .Values.autoscaling.job.advanced) | nindent 4 }}
  triggers:
    - type: redis
      metadata:
        port: {{ .Values.redis.port | quote }}
        hostFromEnv: OOR_REDIS_HOST
        passwordFromEnv: OOR_REDIS_PASSWORD
        usernameFromEnv: OOR_REDIS_USER
        listName: set-{{ $name }}
        listLength: {{ toString ($configValues.autoscalingListLength | default .Values.autoscaling.job.listLength) | quote }}
    - type: cpu
      metricType: Utilization
      metadata:
        value: {{ .Values.autoscaling.job.targetCPUUtilizationPercentage | quote }}
{{- end }}
{{- end }}
{{- end }}
