apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "product-price.fullname" . }}-populate-entities
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "product-price.labels" . | nindent 4 }} populate-entities
data:
  PPS_APP_ENV: {{ .Values.app.env | quote }}
  PPS_LOG_LEVEL: {{ .Values.app.logLevel | quote }}
  PPS_LOG_FORMAT: {{ .Values.app.logFormat | quote }}
  PPS_POSTGRES_DB_HOST: {{ .Values.postgres.masterHost | quote }}
  PPS_POSTGRES_DB_NAME: {{ .Values.postgres.dbName | quote }}
  PPS_POSTGRES_DB_USER: {{ .Values.postgres.user | quote }}
  PPS_RABBITMQ_HOST: {{ .Values.rabbitmq.host | quote }}
  PPS_RABBITMQ_PORT: {{ .Values.rabbitmq.port | quote }}
  PPS_RABBITMQ_USER: {{ .Values.rabbitmq.user | quote }}
  PPS_RABBITMQ_VIRTUAL_HOST: {{ .Values.rabbitmq.virtualhost | quote }}
  PPS_RABBITMQ_EXCHANGE_NAME: {{ .Values.rabbitmq.exchange | quote }}
  PPS_RABBITMQ_PREFETCH_COUNT: {{ .Values.rabbitmq.prefetchCount | quote }}
  PPS_RABBITMQ_ENTITY_SERVER_MAP: {{ .Values.rabbitmq.entities | toJson | squote }}
  PPS_RABBITMQ_QUEUE_POSTFIX: {{ .Values.rabbitmq.queuePostfix | quote }}
  PPS_TARGET_ROUTING_KEY_MAP:  {{ .Values.entityPopulation.targetRoutingKeyMap | toJson | squote }}
  PPS_REPLY_TO_ROUTING_KEY: {{ .Values.entityPopulation.replyToRoutingKey | quote }}
  PPS_REPUBLISH_TO_ROUTING_KEY_MAP: {{ .Values.entityPopulation.republishToRoutingKeyMap | toJson | squote }}
  PPS_USER_AGENT: {{ .Values.entityPopulation.userAgent | quote }}
  PPS_REPUBLISH_BATCH: {{ .Values.entityPopulation.republishBatch | quote }}
  PPS_SENTRY_DSN: {{ .Values.sentry.dsn | quote }}
