apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "product-price.fullname" . }}-worker
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "product-price.labels" . | nindent 4 }} worker
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: {{ .Release.Namespace }}
    kind: SecretStore
  target:
    name: {{ include "product-price.fullname" . }}-worker
  data:
    - secretKey: PPS_POSTGRES_DB_PASSWORD
      remoteRef:
        key: kv-product-price/postgresql
        property: DATABASE_PASSWORD
    - secretKey: PPS_REDIS_PASSWORD
      remoteRef:
        key: kv-product-price/redis
        property: REDIS_PASSWORD
